import type { Metadata } from "next"
import "./globals.css"
import { Providers } from "@/providers/providers"
import type React from "react"
import { InterFont } from "@/lib/fonts"
import Navbar from "@/components/navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={`${InterFont.variable} antialiased`}>
    <Providers>
      <Navbar />
      {children}
    </Providers>
    </body>
    </html>
  )
}
